### ISSUE TITLE
Missing Icons for multiple StrategyTypes and a few Buffs

### ISSUE THREAD

**Issue by infraredsqy** [IsleGames/Sortilege#25]
List of icons missing:

StrategyType.None     
StrategyType.Detriment
StrategyType.Berserker
StrategyType.Craftsman
StrategyType.Knight   
StrategyType.Sorcerer 

BuffType.Forge
BuffType.NoCardsDrawn

Related to #21 & #19

**Comment by ariel215** [comment]
Todo:

- [x] Craftsman
- [x]  Knight
- [x]  Berserker
- [ ] Sorcerer
- [x]  Forge
- [ ]  No Cards
- [x]  Detriment
- [ ] None
